In [66]:
#NUMPYをインポート
import numpy as np

#2次元配列を作成
A = np.array([
 [0,1],
 [2,3],
 [4,5]
 ])
print(f"Aの配列は:")
for i in A:
  print(i)

B = np.array([
 [0,1,2,3],
 [4,5,6,7]
 ])
print(f"----------")
print(f"Bの配列は:")
for i in B:
  print(i)

#積を出す
AB_product = np.dot(A,B)
print(f"-----------")
print(f"AとBの積は:")
for i in AB_product:
  print(i)

#最大値を出す
AB_MAX=AB_product.max()
print(f"------------------")
print(f"行列要素の最大値は:")
print(AB_MAX)

Aの配列は:
[0 1]
[2 3]
[4 5]
----------
Bの配列は:
[0 1 2 3]
[4 5 6 7]
-----------
AとBの積は:
[4 5 6 7]
[12 17 22 27]
[20 29 38 47]
------------------
行列要素の最大値は:
47
